### ISSUE TITLE
buildPlaceOrderMessage params?

### ISSUE THREAD

**Issue by avii-ahuja-ac** [vertex-protocol/vertex-typescript-sdk#184]
I'm trying to place an order using the gateway websocket using the Typescript SDK, but I'm not able to generate a websocket place order message via the SDK.

What should the params of that be?
`vertexClient.ws.execute.buildPlaceOrderMessage({????}) `

the docs don't have anything and I couldn't find any examples either. Please advise on how to proceed.

**Comment by yruej301** [comment]
hey, we have an example here: https://github.com/vertex-protocol/vertex-sdk/blob/799480ef62627a307d69180e283c3f67a5725cf1/apps/e2e/src/client/wsSanity.ts#L33

```typescript
// Websocket payloads
  const wsOrder = {
    ...orderParams,
    subaccountOwner: await signer.getAddress(),
    nonce: getOrderNonce(),
  };

  console.log(`WS Order ${JSON.stringify(wsOrder, null, 2)}`);

  const wsOrderSig = await vertexClient.context.engineClient.sign(
    'place_order',
    verifyingAddr,
    chainId,
    wsOrder,
  );

  const wsPlaceOrderReq = vertexClient.ws.execute.buildPlaceOrderMessage({
    productId: 1,
    order: wsOrder,
    signature: wsOrderSig,
  }).payload;

  console.log(
    `Place Order WS request: ${JSON.stringify(wsPlaceOrderReq, null, 2)}`,
  );
```
